app:
    resource: '@AppBundle/Controller/'
    type: annotation


logout:
    path: /logout


aboutus:
    path: /about-us
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: static/aboutus.html.twig